Address Scope Function Rules
banksalad/styleguide pull request #31
Opened 2021-02-09 09:16 UTC by SODA1127

코드리뷰를 하던 중 [https://github.com/banksalad/banksalad-android/pull/5418#discussion_r572667668](PR 코멘트에서) Scope Function에 대한 Rule이 ambiguously함을 느끼고 리뷰를 통해 Rule을 반영하고자 합니다.

해당 규칙에 대한 반영은 [Kotlin Scoping Functions apply vs. with, let, also, and run](https://medium.com/@fatihcoskun/kotlin-scoping-functions-apply-vs-with-let-also-run-816e4efb75f5) 문서를 참고하였습니다.

안드로이드팀 멤버 분들의 피드백을 받기 위해 태그하여 토론 후 결정합니다.

@banksalad/android

2021-02-09 09:19 UTC, myung6024 commented on android/README.md
> +특정 객체가 **복수로 사용되는 경우**에서만 사용합니다.
이렇게 사용하던 것은
```
something?.let {
      it.do()
}
```
이렇게 사용해야 하나요?
```
if (something != null) {
     something.do()
}
```

2021-02-09 09:23 UTC, SODA1127 commented on android/README.md
> +특정 객체가 **복수로 사용되는 경우**에서만 사용합니다.
@myung6024 let 함수의 경우 충분히 특정객체가 단수여도 사용이 유용할것 같은데, Optional Check 목적인경우 예외로 허가하는것은 어떨까요?

2021-02-09 09:23 UTC, myung6024 commented on android/README.md
> +특정 객체가 **복수로 사용되는 경우**에서만 사용합니다.
https://medium.com/mobile-app-development-publication/kotlin-dont-just-use-let-7e91f544e27f
이런 아티클도 있긴 하더라구요

2021-02-09 09:24 UTC, pjhjohn requested changes
**RC as Merge Blocker**

`Q` 이 규칙을 코드 작성 및 리뷰 단계에서 얼마나 꼭 지켜져야 하는 것인지에 대한 기준 제안이 없어서 내용이 좀 더 보강되면 좋겠습니다. 당장의 느낌은 **강제라면 너무 딱딱하다** 입니다. 공식 문서의 컨벤션을 기본으로 할 수는 있지만, 꼭 우리가 추구해야 할 가치는 아닐 수 있습니다.

저는 이 규칙이 추구하는 가치가 가독성 향상이 되어야 한다고 보는데, 이 규칙을 엄격하게 지키는 것이 가독성 확보의 필수 조건도, 충분 조건도 아니라서 조금 조심스럽습니다.

2021-02-09 09:27 UTC, SODA1127 commented
> **RC as Merge Blocker**
> 
> `Q` 이 규칙을 코드 작성 및 리뷰 단계에서 얼마나 꼭 지켜져야 하는 것인지에 대한 기준 제안이 없어서 내용이 좀 더 보강되면 좋겠습니다. 당장의 느낌은 **강제라면 너무 딱딱하다** 입니다. 공식 문서의 컨벤션을 기본으로 할 수는 있지만, 꼭 우리가 추구해야 할 가치는 아닐 수 있습니다.
> 
> 저는 이 규칙이 추구하는 가치가 가독성 향상이 되어야 한다고 보는데, 이 규칙을 엄격하게 지키는 것이 가독성 확보의 필수 조건도, 충분 조건도 아니라서 조금 조심스럽습니다.

당연하게도 강제라면 저도 반대이긴합니다만(상황에 따라 적절한 대안은 있을것이기 떄문에), 권장사항으로 가져가면 좋겠다는 생각입니다. 규칙이 아닌 지향점으로 문구를 바꿔서 제안해본다면 어떨지 싶습니다.

2021-02-09 09:28 UTC, pjhjohn commented on android/README.md
> +**여러 범위 지정 함수 결합**
여러 범위 지정 함수 결합이 대체... 무슨 뜻인가요...?
[레퍼런스 블로그 글](https://medium.com/@fatihcoskun/kotlin-scoping-functions-apply-vs-with-let-also-run-816e4efb75f5)의 **Combining Multiple Scoping Functions** 인가요?

문장이 굉장히 번역투라서... 다듬을 필요가 있겠네요. Keyword는 그냥 영어를 유지하는 쪽이 더 좋을 것 같습니다.

2021-02-09 09:29 UTC, SODA1127 commented on android/README.md
> +**여러 범위 지정 함수 결합**
@pjhjohn 키워드정도는 영어로 처리하는 것이 훨씬 readable하네요. 수정하겠습니다.

2021-02-09 09:32 UTC, pjhjohn commented
> 당연하게도 강제라면 저도 반대이긴합니다만(상황에 따라 적절한 대안은 있을것이기 떄문에), 권장사항으로 가져가면 좋겠다는 생각입니다. 규칙이 아닌 지향점으로 문구를 바꿔서 제안해본다면 어떨지 싶습니다.

@SODA1127 넵, 이 부분 한번 이야기해 봅시다. 우리가 일하면서 Style Guide / Convention / Lint 등의 다양한 규칙을 만들게 되는데, 각 Statement의 Level 을 정하고, 이 레벨을 Pn 에 매핑하는 방향으로 의견 수렴해야 직관적이면서도 일관적인 코드 리뷰를 진행할 수 있을 듯 합니다. 이것까지 함께 정할 수 있으면 제일 좋겠네요! 제안 너무 좋습니다 👍

2021-02-09 09:39 UTC, SODA1127 commented on android/README.md
> +**여러 범위 지정 함수 결합**
> > 당연하게도 강제라면 저도 반대이긴합니다만(상황에 따라 적절한 대안은 있을것이기 떄문에), 권장사항으로 가져가면 좋겠다는 생각입니다. 규칙이 아닌 지향점으로 문구를 바꿔서 제안해본다면 어떨지 싶습니다.
> 
> @SODA1127 넵, 이 부분 한번 이야기해 봅시다. 우리가 일하면서 Style Guide / Convention / Lint 등의 다양한 규칙을 만들게 되는데, 각 Statement의 Level 을 정하고, 이 레벨을 Pn 에 매핑하는 방향으로 의견 수렴해야 직관적이면서도 일관적인 코드 리뷰를 진행할 수 있을 듯 합니다. 이것까지 함께 정할 수 있으면 제일 좋겠네요! 제안 너무 좋습니다 👍

@pjhjohn  넵, 요 문서를 기반으로 챕터 위클리에 각자의 의견을 들어보고 땅땅하면 될것 같습니다!

위에서 주신 피드백에 따라 추가 수정했습니다. https://github.com/banksalad/styleguide/pull/31/commits/2f23a503deb237e5505de725f328689b91daac2e

2021-02-10 03:42 UTC, SODA1127 commented on android/README.md
> +특정 객체가 **복수로 사용되는 경우**에서만 사용합니다.
@myung6024 디테일하게 한번 읽어보겠습니다!!

2021-02-24 07:41 UTC, pjhjohn commented
@SODA1127 Chapter Weekly 논의에 따라 Closing 하면 될 것 같습니다. 챙겨주세요~!! 🙏

2021-03-31 12:20 UTC, JungWinter commented
@pjhjohn 위클리 논의가 어떻게 된지 잘 모르겠지만 이거 close 하겠습니다!

2021-03-31 12:20 UTC, closed without merging