[EDF-776] Update a git style guide
banksalad/styleguide pull request #33
Opened 2021-02-19 02:17 UTC by pitzcarraldo

[#chapter_tech slack thread](https://rainist.slack.com/archives/C0324HT1Z/p1613444972409000)에서 논의된 결과를 바탕으로 git commit message style guide를 git usage guide로 수정하였습니다.

- commit message parttern Jira Ticket 포함하도록 업데이트.
- [Onboarding 문서](https://docs.google.com/document/d/1D6krUNvFrFHbJ1y040Rz8BZj2eqj-j_ORNXNQQ7zNns)에 있던 PR convention 관련 내용을 포함.
- commit message, branch naming checking git hook script 추가.

이 PR이 merge되면 [Onboarding 문서](https://docs.google.com/document/d/1D6krUNvFrFHbJ1y040Rz8BZj2eqj-j_ORNXNQQ7zNns)의 PR관련 부분은 이 문서를 참조하도록 업데이트 할 예정입니다.

2021-02-19 02:21 UTC, sunghyunzz approved these changes
미리 승인하겠습니다. 잘 작성해주셔서 감사합니다 👍

2021-02-19 02:21 UTC, sunghyunzz commented on git/install_hooks.sh
> +chmod +x .git/hooks/prepare-commit-msg
```suggestion
chmod +x .git/hooks/prepare-commit-msg

```
P2; 개행열 챙겨야할 것 같습니다.

2021-02-19 02:22 UTC, kanziw commented on git/README.md
> +[JIRA-123] Short (50 chars or less) summary of changes
p3; Squash merge 를 사용하기에 PR title 에만 Jira ticket 이 들어가도 괜찮지 않나~ 하는 생각은 있습니다. commit message 엔 jira ticket 없이 가는건 어떠세요?

2021-02-19 02:22 UTC, kanziw commented on git/install_hooks.sh
> +chmod +x .git/hooks/prepare-commit-msg
nit; EOF 🙏

2021-02-19 02:31 UTC, sean-ahn commented on git/README.md
> +[JIRA-123] Short (50 chars or less) summary of changes
P2; 아래와 같은 이유로
* JIRA ticket 의 단위는 최소한 commit 단위보다 크고, (아마 PR)
* Squash merge 를 하게 되는 순간 PR title 이 squash merge commit 의 message 가 되고
* PR 내 commit message 가 optional description message 에 들어가긴 하지만 이를 확인하는 경우는 거의 없기 때문에

저는 생산성을 위해 squash merge 를 사용하는 상황에서 commit message 에 대한 룰은 제거하는 것이 맞다고 생각합니다. 다른 분들 의견도 들어보고 싶습니다.

2021-02-19 02:39 UTC, kanziw requested changes

2021-02-19 02:39 UTC, kanziw commented on git/README.md
> +```
p3; 저희 요 repository 의 경우는 public 이기에 토큰은 없어도 동작하게 될 것 같습니다 🙏

2021-02-19 02:39 UTC, kanziw commented on git/README.md
> +  - [Pull Request 리뷰 관련 쓰레드](https://rainist.slack.com/archives/C0324HT1Z/p1582118248184200)
p2; public repository 이기에 저희 구글문서나 슬랙 링크는 동작하지 않을 예정입니다ㅜ
p3; "더 나은 코드 리뷰 문화를 위한 제언" 문서는 아예 이 repository 로 옮겨 공개하는건 어떠세요? @sunghyunzz @xissy

2021-02-19 02:45 UTC, sunghyunzz commented on git/README.md
> +  - [Pull Request 리뷰 관련 쓰레드](https://rainist.slack.com/archives/C0324HT1Z/p1582118248184200)
아하 해당 문서 텍스트 조금 다듬어서 Google Docs를 외부인에게도 공개 및 추후 기술블로그 글 작성해도 좋겠네요.

2021-02-19 06:10 UTC, pitzcarraldo commented on git/README.md
> +[JIRA-123] Short (50 chars or less) summary of changes
네 그럼 commit에 대한 훅은 빼고 준호님 스레드를 참고하여 github hook을 통해 PR naming을 검증하도록 수정해보겠습니다~

2021-02-23 06:45 UTC, pitzcarraldo commented on git/README.md
> +[JIRA-123] Short (50 chars or less) summary of changes
Commit naming hook을 빼고 Pull Request Naming Check를 추가하였습니다.

2021-02-23 06:46 UTC, pitzcarraldo commented on git/README.md
> +  - [Pull Request 리뷰 관련 쓰레드](https://rainist.slack.com/archives/C0324HT1Z/p1582118248184200)
회사 내부에서만 접근가능한 문서들의 링크를 제외했습니다. 해당 문서 링크들은 추후 git으로 이전 후에 다시 추가하면 될 것 같습니다.

2021-02-23 06:50 UTC, kanziw approved these changes

2021-02-24 05:08 UTC, kanziw approved these changes

2021-02-24 05:08 UTC, kanziw commented on git/workflows/pull-request-lint.yml
> +    runs-on: ubuntu-latest
nit; GitHub 이 주는 GitHub Actions quota 가 저희의 사용량을 따라오지 못하고, 또한 quota 관련 GitHub 쪽 버그가 있었어서 저희 내부 대부분의 서비스는 self-hosted runner 를 사용하고 있긴 합니다. 하지만 styleguide repository 가 public 이기도 하고 요 lint 를 돌릴 정도는 감당할 수 있지 않을까 싶어 괜찮지 않을까.. 싶긴 합니다. GitHub Actions quota 정보들 따로 슬랙 통해 공유드리겠습니다~

2021-02-24 05:37 UTC, JungWinter commented on .github/workflows/pull-request-lint.yml
> +name: 'Pull Request Lint'
ask; 저는 styleguide가 public 레포다보니 외부인의 기여도 있을 수 있고, 외부인은 jira ticket number를 pr 제목으로 달 수 없을테니 이 actions는 styleguide github actions로 있기보단 참고용으로 `git`폴더 내부에 `lint-example.yml`로 존재하거나 따로 템플릿 레포에 있어야한다고 생각했습니다.

혹시 styleguide 특성상 주로 내부인의 기여만 받고있기에 추가해두신걸까요?

2021-02-24 05:37 UTC, JungWinter commented on git/README.md
> +- Pull Request를 open할 때는 master에 바로 머지될 수 있는 코드들만 open합니다.
```suggestion
- Pull Request를 open할 때는 main 브랜치에 바로 머지될 수 있는 코드들만 open합니다.
```
p5;

2021-02-24 05:37 UTC, JungWinter commented on git/hooks/prepare-commit-msg
> +master_branch="master"
```suggestion
main_branch="main"
```
ask; 저는 앞으로 github repository의 default branch name은 `main`이기에 여기서도 일단 main으로 가면 어떤가 하는 생각이 있는데, 반대로 지금 뱅크샐러드의 거의 모든 레포는 `master`로 쓰고있기에 master로 가는게 효용이 높겠다 하는 생각도 있습니다. 민규님은 어떻게 생각하세요?

2021-02-24 05:37 UTC, JungWinter commented on git/install_hooks.sh
> +curl -o .github/workflows/pull-request-lint.yml \
```suggestion
curl -o git/workflows/pull-request-lint.yml \
```
ask; 뭔가 이런걸 의도하셨을까요?

2021-02-24 05:37 UTC, JungWinter commented on git/hooks/prepare-commit-msg
> +branch_regexp="^[A-Z]+\-[0-9]+\-.+$"
```suggestion
branch_regexp="^[A-Z]{1}[A-Z0-9]{1,9}\-[0-9]+\-.+$"
```
p4; pr lint actions과 맞춰서 이렇게는 어떠세요?

2021-02-24 05:53 UTC, kanziw commented on git/hooks/prepare-commit-msg
> +master_branch="master"
요렇게는 어떠세요? 예전에 stackoverflow 에서 발견했던 코드고 제가 개인적으로 쓰는 스크립트에서 요렇게 쓰고있습니다.

```
default_branch=$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')
```

2021-02-24 06:29 UTC, pitzcarraldo commented on .github/workflows/pull-request-lint.yml
> +name: 'Pull Request Lint'
처음엔 이 repo가 public인지 모르고 작업을 시작 했는데요, public repo라는것을 알고 난 이후에 저도 이부분들에 대해 고민이 많았습니다. styleguide는 변경을 하지 말고 hook/workflow만 별도 private repo로 만들어서 관리하면 어떨까요? 이PR은 그냥 close 하구요.
@kanziw @sunghyunzz

2021-02-24 06:54 UTC, kanziw commented on .github/workflows/pull-request-lint.yml
> +name: 'Pull Request Lint'
우리의 일하는 방식에 대한 내용은 styleguide 에 있는게 어색하다고 느껴지진 않습니다. 다만 (전 생각지도 못하긴 했는데 ^^;;) 겨울님이 말씀주신 것처럼 이 repo 에 해당 action 을 추가하는건 어색할 수 있겠단 생각이 드네요.ㅎㅎ

hook/workflow 에 대한 내용만 요 레포에서 private github actions 를 관리하는 레포로 옮겨가는건 어떠세요?

2021-02-24 06:57 UTC, pitzcarraldo commented on .github/workflows/pull-request-lint.yml
> +name: 'Pull Request Lint'
@kanziw 그것도 좋을거 같아요. Hook관련 부분만 이 문서에서 제외하고 피드백 반영해서 업데이트 하겠습니다.

2021-02-24 07:04 UTC, pitzcarraldo commented on git/hooks/prepare-commit-msg
> +master_branch="master"
해당 내용은 private github actions repo로 이동할 때 반영하겠습니다.

2021-02-24 07:04 UTC, pitzcarraldo commented on git/hooks/prepare-commit-msg
> +branch_regexp="^[A-Z]+\-[0-9]+\-.+$"
해당 내용은 private github actions repo로 이동할 때 반영하겠습니다.

2021-02-24 07:49 UTC, pjhjohn requested changes
몇 가지 문장 다듬기 + 내용 추가를 제안해 봅니다.

2021-02-24 07:49 UTC, pjhjohn commented on git/README.md
> +뱅크샐러드에서는 브랜치 전략으로 git flow를 사용하지 않고 있습니다. 빠른 배포를 위해, 필요한 코드에 대해 브랜치만 생성해서 작업 후에 머지하는 방식을 채택해 진행하고 있습니다.
```suggestion
뱅크샐러드에서는 Android / iOS 등 Mono-repo를 사용하는 팀을 제외하고는 기본적으로 브랜치 전략으로 Git Flow를 사용하지 않고 있습니다. 빠른 배포를 위해, 필요한 코드에 대해 브랜치만 생성해서 작업 후에 머지하는 방식을 채택해 진행하고 있습니다.
```
`P3` @banksalad/android @banksalad/ios 는 Git Flow 전략을 여전히 사용하고 있습니다.

2021-02-24 07:49 UTC, pjhjohn commented on git/README.md
> +  전략 을 사용 중이기 때문에 Pull Request의 title이 main 브랜치의 커밋 메시지가 됩니다.
```suggestion
  전략을 사용하고 있으므로 Pull Request의 title이 main 브랜치의 커밋 메시지가 됩니다.
  (단, 1 Commit PR인 경우에만 예외적으로 해당 Commit이 곧 Merged Commit Title이 됩니다.)
```
Edge Case 추가해 봅니다.

2021-02-24 07:49 UTC, pjhjohn commented on git/README.md
> +    - title, description에 jira ticket key를 명시
```suggestion
    - title, description에 jira ticket issue key를 명시
```

2021-02-24 07:49 UTC, pjhjohn commented on git/README.md
> +    - 장애가 발생한 경우에 어떤 커밋 때문에 장애가 발생했는지 알지 못하기 때문에 여러개의 커밋 한번에 롤백해야하는 상황이 발생합니다.
```suggestion
    - 장애가 발생한 경우에 어떤 커밋 때문에 장애가 발생했는지 알지 못하기 때문에 여러개의 커밋을 한번에 롤백해야하는 상황이 발생합니다.
```

2021-02-25 04:09 UTC, pitzcarraldo commented
@sunghyunzz @kanziw @JungWinter @pjhjohn 
이 PR이 좀 오래 열려있는 것 같아서 추가 피드백 없으시면 approve 부탁드립니다~ :)

2021-02-25 04:10 UTC, pjhjohn approved these changes

2021-02-25 04:14 UTC, kanziw approved these changes

2021-02-25 04:15 UTC, merged